OUTDIR: 
  fastq_pooled
NEXTSEQDIR: 
  mynextseqdir
FILTER:
  cutadapt:
      adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
      quality-filter: 20
      minimum-adapters-overlap: 6
      minimum-length: 15
      maximum-length: 40
      extra-params:

# AGATCGGAAGAGC

# Changed the Illumina small RNA sequence used for auto-detection to 'TGGAATTCTCGG' (from formerly 'ATGGAATTCTCG'). 
# The reason for this is that smallRNA libraries have ssRNA adapters ligated to their -OH end, a signature of dicer cleavage, so there is no A-tailing involved. Thanks to Q. Gouil for bringing this to our attention
# f ($nextera){
# $adapter = 'CTGTCTCTTATA';
# $adapter_name = 'Nextera Transposase sequence; user defined';
# }
# elsif($small_rna){
# $adapter = 'TGGAATTCTCGG';
# $adapter_name = 'Illumina small RNA adapter; user defined';
# }
# elsif($illumina){
# $adapter = 'AGATCGGAAGAGC';
# $adapter_name = 'Illumina TruSeq, Sanger iPCR; user defined';
