THREADS: 32
FILTER:
  cutadapt:
      adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
      quality-filter: 20
      minimum-adapters-overlap: 6
      minimum-length: 15
      maximum-length: 40
      extra-params:
MAPPING:
      # default
      # -k 1 (default): Report up to <int> valid alignments per read
      # options for mode are "unique" and "multi"
      mode: "multi" # passed on to bowtie as `bowtie -m 1` if unique, otherwise default
      missmatches: 0 # passed on to bowtie as `bowtie -v <int>`
      reference: "data/index/genome"

# Changed the Illumina small RNA sequence used for auto-detection to 'TGGAATTCTCGG' (from formerly 'ATGGAATTCTCG'). 
# ($nextera){
# $adapter = 'CTGTCTCTTATA';
# $adapter_name = 'Nextera Transposase sequence; user defined';
# }
# elsif($small_rna){
# $adapter = 'TGGAATTCTCGG';
# $adapter_name = 'Illumina small RNA adapter; user defined';
# }
# elsif($illumina){
# $adapter = 'AGATCGGAAGAGC';
# $adapter_name = 'Illumina TruSeq, Sanger iPCR; user defined';
