channels:
  - bioconda
  - conda-forge
dependencies:
  - fastx_toolkit
  - bowtie=1
  - cutadapt
  - fastqc
  - multiqc
  - samtools
  - bamtools
  # - ucsc-bedgraphtobigwig
  # - bedtools
  - deeptools>=3
  - snakemake>=5.20
